using Remedy.Framework;
using Remedy.Schematics;
using System.Collections.Generic;
using UnityEngine;

public class GlobalSchematicManagerData : SingletonData<GlobalSchematicManagerData>
{
    [Tooltip("The Schematic Prefabs generated by the Schematics system from the FlowGraphEditorWindow. (Key: GameObject Prefab - " +
        "Value: SchematicScope Asset)")]
    [SerializeField]
    private SerializableDictionary<GameObject, SchematicGraph> _schematicPrefabs = new();
    public static SerializableDictionary<GameObject, SchematicGraph> SchematicPrefabs => Instance._schematicPrefabs;

    [SerializeField]
    private SerializableDictionary<GameObject, List<int>> _prefabIOBases = new();
    public static SerializableDictionary<GameObject, List<int>> PrefabIOBases => Instance._prefabIOBases;

    [Tooltip("The Singletons Objects created by the Schematic Editor")]
    [SerializeField]
    private SchematicInstanceController[] Singletons = new SchematicInstanceController[0];

    [SerializeField, HideInInspector]
    private List<SingletonGraph> _singletonGraphs;
    public static List<SingletonGraph> SingletonGraphs => Instance._singletonGraphs ??= new();

    public static void AddSingletonGraph(SingletonGraph graph)
    {
        if(Application.isPlaying)
            Instance._singletonGraphs.RemoveAll(item => item == null);

        if (!Instance._singletonGraphs.Contains(graph))
        {
            Instance._singletonGraphs.Add(graph);
        }
    }
}